from sentence_transformers import SentenceTransformer, util
from core_engine.smart_match.schemas import SmartMatchRequest, SmartMatchResponse

class SmartMatchService:
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        # Load a lightweight, high-performance model
        self.model = SentenceTransformer(model_name)

    async def calculate_match(self, request: SmartMatchRequest) -> SmartMatchResponse:
        """
        Calculates the semantic match using Sentence-Transformers embeddings.
        """
        # Generate embeddings
        resume_emb = self.model.encode(request.resume_text, convert_to_tensor=True)
        jd_emb = self.model.encode(request.jd_text, convert_to_tensor=True)
        
        # Calculate cosine similarity
        cosine_score = util.cos_sim(resume_emb, jd_emb).item()
        
        # Convert to 0-100 scale
        overall_score = round(max(0, cosine_score) * 100, 2)
        
        # Heuristic-based justification for the prototype
        # In a full RAG setup, this would be generated by a local LLM
        justification = [
            f"Semantic similarity score of {overall_score}% indicates a strong alignment in core competencies." if overall_score > 70 else 
            f"Moderate alignment ({overall_score}%) with the job requirements. Some skill gaps identified."
        ]
        
        # Mocking skill extraction for now (requires a taxonomy or LLM)
        # We'll use basic keyword extraction from the JD text for the prototype
        matched_skills = ["Python", "FastAPI"] # Placeholder
        missing_skills = ["Kubernetes", "AWS"] # Placeholder
        recommendations = [
            "Enhance your profile by adding hands-on experience with missing cloud technologies.",
            "Quantify your impact in previous roles using the STAR method.",
            "Consider obtaining industry-standard certifications mentioned in the JD."
        ]
        
        return SmartMatchResponse(
            overall_score=overall_score,
            justification=justification,
            matched_skills=matched_skills,
            missing_skills=missing_skills,
            recommendations=recommendations
        )

# Singleton instance
smart_match_service = SmartMatchService()
